security:
  enable_authenticator_manager: true

  role_hierarchy:
    ROLE_EMPLOYE: []

  password_hashers:
    App\Entity\Utilisateur:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false

    public_api:
      pattern: ^/(?:api/utilisateurs$|api/utilisateurs/connexion$)
      security: false
      stateless: true

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\ApiTokenAuthenticator

    public_front:
      pattern: ^/(?:$|connexion|inscription|contact|mentions-legales|mon-compte|mes-covoiturages|proposer-trajet|employe|voitures/ajouter|covoiturages(?:/.*)?)
      security: false

    main:
      pattern: ^/
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: connexion
        check_path: connexion
        default_target_path: mon_compte
      logout:
        path: app_logout

  access_control:
    - { path: ^/api/utilisateurs$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - {
        path: ^/api/utilisateurs/connexion$,
        roles: IS_AUTHENTICATED_ANONYMOUSLY,
      }
    - { path: ^/api/covoiturages, roles: ROLE_USER }
    - { path: ^/api, roles: ROLE_USER }
    - { path: ^/employe$, roles: ROLE_EMPLOYE }
    - { path: ^/proposer-trajet, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/mes-covoiturages, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/covoiturages, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
