# .platform.app.yaml
name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"

dependencies:
  php:
    composer/composer: "^2"

hooks:
  build: |
    set -e
    export APP_ENV=prod APP_DEBUG=0 COMPOSER_SKIP_AUTOSCRIPTS=1
    composer install --no-dev --no-scripts --prefer-dist --no-progress --optimize-autoloader --ignore-platform-req=ext-mongodb
  deploy: |
    set -e
    export APP_ENV=prod APP_DEBUG=0
    php bin/console doctrine:migrations:migrate --no-interaction --env=prod
    php bin/console cache:clear --env=prod

mounts:
  "/var": "shared:files"
