# .platform.app.yaml
name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
    CORS_ALLOW_ORIGIN: "^https?://([^/]+\\.)?main-bvxea6i-rm5gtsnixyao4\\.fr-3\\.platformsh\\.site$"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"

dependencies:
  php:
    composer/composer: "^2"

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --no-progress --prefer-dist --optimize-autoloader --ignore-platform-req=ext-mongodb

  deploy: |
    set -e
    # Nettoyage du cache et des logs
    rm -rf var/cache/* var/log/*
    mkdir -p var/cache var/log

runtime:
  extensions:
    - gd
    - intl
    - pdo
    - pdo_mysql
    - opcache
    - mongodb
