# .platform.app.yaml
name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
    CORS_ALLOW_ORIGIN: "^https?://([^/]+\\.)?main-bvxea6i-rm5gtsnixyao4\\.fr-3\\.platformsh\\.site$"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"

dependencies:
  php:
    composer/composer: "^2"

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --no-progress --prefer-dist --optimize-autoloader

  deploy: |
    set -e
    # 1. Supprime le contenu du cache généré pendant le build
    #    (Le fait de vider le dossier est plus sûr que de tenter de changer les permissions)
    rm -rf var/cache/* var/log/*

    # 2. S'assure que les dossiers existent.
    #    Platform.sh garantit que l'utilisateur www-data a accès en écriture 
    #    à l'intérieur du volume /var (grâce au mount).
    mkdir -p var/cache var/log
