name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
    CORS_ALLOW_ORIGIN: "^https?://([^/]+\\.)?main-bvxea6i-rm5gtsnixyao4\\.fr-3\\.platformsh\\.site$"
    DATABASE_URL: "mysql://user:pass@127.0.0.1:3306/dummy?charset=utf8mb4"
    MONGODB_URL: "mongodb://127.0.0.1:27017"
    MONGODB_DB: "dummy"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"
  mongodb: "mongodb:mongodb"

dependencies:
  php:
    composer/composer: "^2"

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --no-progress --prefer-dist --optimize-autoloader

  deploy: |
    set -e
    rm -rf var/cache/*
    php bin/console doctrine:mongodb:generate:proxies
    php bin/console cache:warmup --env=prod
    php bin/console assets:install public --symlink --relative
    rm -rf var/log/*

runtime:
  extensions:
    - gd
    - intl
    - pdo
    - pdo_mysql
    - opcache
    - mongodb
