# .platform.app.yaml
name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"

dependencies:
  php:
    composer/composer: "^2"

hooks:
  build: |
    printf "APP_ENV=prod\nAPP_DEBUG=0\n" > .env
    composer install --no-dev --prefer-dist --no-interaction --no-progres

mounts:
  "/var": "shared:files"
