name: app
type: php:8.2
disk: 2048

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
    # Garde ton CORS si utile, mais surtout NE PAS définir DATABASE_URL / MONGODB_URL en dur
    CORS_ALLOW_ORIGIN: "^https?://([^/]+\\.)?main-bvxea6i-rm5gtsnixyao4\\.fr-3\\.platformsh\\.site$"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"
  mongodb: "mongodb:mongodb"

dependencies:
  php:
    composer/composer: "^2"
    platformsh/config-reader: "^2"

mounts:
  "/var": "shared:files"

build:
  flavor: none

hooks:
  build: |
    set -e
    composer install --no-progress --prefer-dist --optimize-autoloader

  deploy: |
    set -e
    rm -rf var/cache/*
    php bin/console cache:warmup --env=prod
    php bin/console assets:install public --symlink --relative
    rm -rf var/log/*

runtime:
  extensions:
    - gd
    - intl
    - pdo
    - pdo_mysql
    - pdo_sqlite
    - opcache
    - mongodb
