# .platform.app.yaml
name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
    CORS_ALLOW_ORIGIN: "^https?://([^/]+\\.)?main-bvxea6i-rm5gtsnixyao4\\.fr-3\\.platformsh\\.site$"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"
  mongodb: "mongodb:mongodb"

dependencies:
  php:
    composer/composer: "^2"

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --no-progress --prefer-dist --optimize-autoloader --ignore-platform-req=ext-mongodb

  deploy: |
    set -e
    export MONGODB_URL=$(php vendor/bin/platformsh-config dump-url --relation=mongodb --database=mongodb)
    export MONGODB_AUTH_SOURCE=$(php vendor/bin/platformsh-config get auth_source --relation=mongodb)
    export MONGODB_DB=$(php vendor/bin/platformsh-config get database --relation=mongodb)
    php bin/console cache:clear --env=prod --no-debug
    php bin/console cache:warmup --env=prod
    rm -rf var/log/*

runtime:
  extensions:
    - gd
    - intl
    - pdo
    - pdo_mysql
    - opcache
    - mongodb
