# .platform.app.yaml
name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"

dependencies:
  php:
    composer/composer: "^2"

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --no-progress --prefer-dist --optimize-autoloader

  deploy: |
    set -e
    # IMPORTANT: Suppression du cache généré lors de la phase de 'build'
    # Cela permet à la phase 'chown' de s'exécuter et à l'utilisateur www-data de recréer le cache.
    rm -rf var/cache/*

    # S'assurer que les dossiers de base existent (et sont vides)
    mkdir -p var/cache var/log

    # Changer la propriété du répertoire MONTÉ pour l'utilisateur web
    # Cela est maintenant possible car 'var' n'est plus rempli de fichiers orphelins.
    chown -R www-data:www-data var
