name: app
type: php:8.2
disk: 1024

build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
    CORS_ALLOW_ORIGIN: "^https?://([^/]+\\.)?main-bvxea6i-rm5gtsnixyao4\\.fr-3\\.platformsh\\.site$"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      scripts: true
      allow: true

relationships:
  database: "db:mysql"
  mongodb: "mongodb:mongodb"

dependencies:
  php:
    composer/composer: "^2"
    platformsh/config-reader: "^2"

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --no-progress --prefer-dist --optimize-autoloader --ignore-platform-req=ext-mongodb --no-scripts
    php vendor/bin/platformsh-config inject-env --prefix=MONGODB_ --relation=mongodb --output-file=var/cache/.env.local.php

  deploy: |
    set -e
    # Le cache clear s'exécute ici. Le MONGODB_URL est maintenant disponible 
    # grâce au fichier .env.local.php généré dans le hook build.
    php bin/console cache:clear --env=prod --no-debug
    php bin/console cache:warmup --env=prod
    rm -rf var/log/*

runtime:
  extensions:
    - gd
    - intl
    - pdo
    - pdo_mysql
    - opcache
    - mongodb
