name: app
type: "php:8.2"
build:
  flavor: none

variables:
  env:
    APP_ENV: "prod"
    COMPOSER_NO_DEV: "1"

runtime:
  extensions:
    - pdo_mysql
    - sodium
    - intl

relationships:
  database: "db:mysql"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"

hooks:
  build: |
    set -e
    # Forcer l'env prod pendant tout le build
    export APP_ENV=prod APP_DEBUG=0

    # Installer les deps sans les scripts, et ignorer l’extension Mongo
    composer install --no-dev --no-scripts --prefer-dist --no-progress --optimize-autoloader --ignore-platform-req=ext-mongodb

    # Notre cycle de cache en prod
    php bin/console cache:clear --env=prod
    php bin/console cache:warmup --env=prod

  deploy: |
    set -e
    php bin/console doctrine:migrations:migrate --no-interaction --env=prod
    php bin/console cache:clear --env=prod
