services:
  php:
    image: php:8.2-fpm
    container_name: ecoride-php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - mongo
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - "9000:9000"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y git unzip libpq-dev libzip-dev libpng-dev libxml2-dev libonig-dev libicu-dev libcurl4-openssl-dev libssl-dev && \
        docker-php-ext-install pdo pdo_mysql intl zip gd && \
        php-fpm
      "

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoride
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  apache:
    build:
      context: .
      dockerfile: docker/Dockerfile-apache
    container_name: ecoride-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - db
      - mongo

volumes:
  db_data:
  mongo_data:
