FROM php:8.2-fpm

RUN apt-get update \
 && apt-get install -y \
    libicu-dev \
    libzip-dev \
    libpng-dev \
    libxml2-dev \
    libonig-dev \
    libcurl4-openssl-dev \
    git unzip curl \
    # ===== paquets MongoDB natif =====
    pkg-config \
    libssl-dev \
    libsasl2-dev \
    libmongoc-dev \
    libbson-dev \
 && docker-php-ext-install intl zip gd pdo pdo_mysql

# Maintenant, on a tout ce qu’il faut pour compiler mongodb avec SSL, SASL, APM…
RUN pecl install mongodb-2.1.1 \
 && docker-php-ext-enable mongodb

WORKDIR /var/www/html
COPY --chown=www-data:www-data . /var/www/html
