FROM php:8.2-apache

# Installer les dépendances système et PHP ext.
RUN apt-get update \
  && apt-get install -y \
    libicu-dev \
    libzip-dev \
    libpng-dev \
    libxml2-dev \
    libonig-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    pkg-config \
    git \
    unzip \
    curl \
  && docker-php-ext-install intl zip gd pdo pdo_mysql

# Installer et activer MongoDB
RUN pecl install mongodb-2.1.1 \
 && docker-php-ext-enable mongodb

# Activer mod_rewrite et ajuster DocumentRoot
RUN a2enmod rewrite
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf

WORKDIR /var/www/html
COPY --chown=www-data:www-data . /var/www/html
