FROM php:8.2-apache

# Dépendances système + extensions PHP
RUN apt-get update \
  && apt-get install -y \
    libicu-dev \
    libzip-dev \
    libpng-dev \
    libxml2-dev \
    libonig-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    pkg-config \
    git unzip curl \
  && docker-php-ext-install intl zip gd pdo pdo_mysql

# --- MongoDB PECL 1.19.1 (compatible avec tes helpers BSON attendus) ---
RUN printf "\n" | pecl uninstall mongodb || true \
 && pecl install mongodb-1.19.1 \
 && docker-php-ext-enable mongodb

# Apache
RUN a2enmod rewrite
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf

WORKDIR /var/www/html
COPY --chown=www-data:www-data . /var/www/html
